services:
  - type: web
    name: url-shortener
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080 # This is safe to keep here.
    # NOTE: MONGO_DB_URI and APP_BASE_URL should be set in the Render Dashboard
    # under the 'Environment' tab for this service.
