services:
  - type: web
    name: url-shortener
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: APP_BASE_URL
        fromSecret: true
      - key: MONGO_DB_URI
        fromSecret: true
